### ISSUE TITLE
Column margin not shown

### ISSUE THREAD

**Issue by ruifengx** [emily-curry/base16-tomorrow-dark-intellij#2]
First, thanks for your effort in this theme!

I normally see a column margin (a vertical line at the column limit, usually 80 or 100) on the right side of the code editor, but when I switch to this theme the line disappears. I can reproduce this by merely switching the theme (without touching other settings), so it is probably a problem here.

**Comment by emily-curry** [comment]
Hey there! I've been wanting to make a few changes to this for a while now, but haven't had the proper motivation. So thanks for logging an issue!

I've fixed this in the latest version (just submitted it, takes about ~2 days to be processed), please let me know if that fixes the issue you're seeing.

**Comment by ruifengx** [comment]
I have updated the plugin, and it works just as expected. Thanks again for your effort!
